services:
  pb:
    # image: alpine:latest
    build: .
    entrypoint: /app/pb/entrypoint.sh
    command: "/app/pb/pocketbase serve --automigrate=false --dev --http 0.0.0.0:8090 --publicDir ../sk/build"
    user: ${UID}:${GID}
    expose:
      - 8090
    working_dir: /app/pb
    environment:
      - RELEASE=${RELEASE:-standard} # use "custom" for main.go build, "standard" for downloaded binary
      - PB_VERSION=0.38.0
      - PB_ARCH=linux_amd64
      - HOME=/app/pb
      - AUDITLOG=${AUDITLOG}
      - PB_SUPERUSER_EMAIL=${PB_SUPERUSER_EMAIL}
      - PB_SUPERUSER_PASSWORD=${PB_SUPERUSER_PASSWORD}
      - PB_USER_EMAIL=${PB_USER_EMAIL}
      - PB_USER_PASSWORD=${PB_USER_PASSWORD}
    volumes:
      - ./pb:/app/pb
      - ./sk:/app/sk
      - ${HOME}/go/pkg:/go/pkg
  sk:
    image: oven/bun:1-alpine
    user: ${UID}:${GID}
    # sveltekit build
    # command: sh -c "bun install && bun run build"
    # for live development
    command: sh -c "bun install && bun run dev -- --host 0.0.0.0"
    expose:
      - 5173
    volumes:
      - ./sk:/app/sk
      - ./pb:/app/pb
    environment:
      - HOME=/app/sk
    working_dir: /app/sk
